"""
Dutch Bank Transaction Merchant Registry
========================================

Format: (search_term, section, category, confidence)
Search terms are UPPERCASE for case-insensitive matching.
"""

MEGA_MERCHANT_MAPPING = [
    # --- Boodschappen/Supermarkt ---
    ('ALBERT HEIJN', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('AH ', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('AH TO GO', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('AH BETAALGEMAK', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('AH ONLINE', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('AH AMSTERDAM', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('AH ROTTERDAM', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('AH UTRECHT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('AH GRONINGEN', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('AH FRESCO', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('JUMBO', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('JUMBO AMSTERDAM', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('JUMBO ROTTERDAM', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('JUMBO SUPERMARKT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('JUMBO ONLINE', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('LIDL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('LIDL NEDERLAND', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('LIDL AMSTERDAM', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('LIDL ROTTERDAM', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('LIDL PLUS', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('ALDI', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('ALDI NEDERLAND', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('ALDI AMSTERDAM', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('ALDI ROTTERDAM', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('PLUS SUPERMARKT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('PLUS AMSTERDAM', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('PLUS ROTTERDAM', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('DIRK VAN DEN BROEK', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('DIRK', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('DEKAMARKT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('COOP SUPERMARKT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('SPAR NEDERLAND', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('SPAR ', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('VOMAR', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('HOOGVLIET', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('NETTORAMA', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('BONI SUPERMARKT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('POIESZ', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('JAN LINDERS', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('PICNIC', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('PICNIC.NL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('CRISP SUPERMARKT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('FLINK', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('FLINK DELIVERY', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('GORILLAS', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('GETIR', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('AH.NL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('JUMBO.NL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('PICNIC ONLINE', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),

    # --- Horeca/Restaurants ---
    ('MCDONALDS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('MCDONALD', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('MCD', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('BURGER KING', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('KFC', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('SUBWAY', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('DOMINOS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('DOMINOS PIZZA', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('NEW YORK PIZZA', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('FEBO', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('VAPIANO', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('HAPPY ITALY', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('LOETJE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CHICKEN KING', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('DURUM', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('DONER KEBAB', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('GRILL', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('PIZZERIA', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('SUSHI', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('RAMEN', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('THAI', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('INDISCH', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CHINEES', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('THUISBEZORGD', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('THUISBEZORGD.NL', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('UBER EATS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('DELIVEROO', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('DELIVEROO.NL', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('STARBUCKS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('COFFEE COMPANY', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('BAGELS & BEANS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('LAPTOPKOFFIE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('ESPRESSO', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CAFE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('KOFFIE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('HEMA RESTAURANT', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('HEMA CAFE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('LA PLACE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('VAN DER VALK', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('FLETCHER HOTELS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('POSTILLION HOTELS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('NH HOTELS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('MARRIOTT', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('HILTON', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('IBIS HOTELS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('NOVOTEL', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('HOLIDAY INN', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('ACCOR HOTELS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CAMPING', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('APARTHOTEL', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CCV*RESTAURANT', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CCV*CAFE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CCV*PIZZA', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CCV*BURGER', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CCV*SUSHI', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CCV*KEBAB', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CCV*CAFE BAR', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('RESTAURANT ', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('RESTAURANT*', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('EETCAFE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('BRASSERIE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),

    # --- Benzine/Diesel/Laden ---
    ('SHELL', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('SHELL STATION', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('BP', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('ESSO', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('TOTAL', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('TINQ', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('TEXACO', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('TANGO', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('GULF', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('AVIA', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('TAMOIL', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('ARGOS', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('FIREZONE', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('JET TANKSTATION', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('ROUTESTOP', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('TRAVELODGE FUEL', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('LAADPAAL', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('EV CHARGING', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('FASTNED', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('IONITY', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('PLUGSURFING', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('CHARGEFOX', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('NEW MOTION', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('JEDLIX', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),
    ('TESLA SUPERCHARGER', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),

    # --- Auto/Mobiliteit ---
    ('EUROPARKING', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('Q-PARK', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('P1 PARKING', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('YELLOWBRICK', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('PARKMOBILE', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('EASYPARK', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('FLOWBIRD', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('PRKNG', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('PARKWHIZ', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('VINCI PARKING', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('ANWB', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),

    # --- Abonnementen/Lidmaatschappen ---
    ('ANWB LIDMAATSCHAP', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),

    # --- Auto/Mobiliteit ---
    ('ROUTE MOBIEL', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),

    # --- Openbaar vervoer ---
    ('NS TREINEN', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('NS ', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('NS.NL', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('GVB AMSTERDAM', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('RET ROTTERDAM', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('HTM DEN HAAG', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('OV-CHIPKAART', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('TRANSLINK', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('ARRIVA', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('CONNEXXION', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('QBUZZ', 'variabele_kosten', 'Openbaar vervoer', 0.9),
    ('KEOLIS BUSSUM', 'variabele_kosten', 'Openbaar vervoer', 0.9),

    # --- Auto/Mobiliteit ---
    ('HERTZ', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('SIXT', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('EUROPCAR', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('RENTALCARS', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('ENTERPRISE RENT A CAR', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('AVIS', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('BUDGET RENT A CAR', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('GREENWHEELS', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('MYWHEELS', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('DEECAR', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('TEILAUTO', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('SNAPPCAR', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('FELYX', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('CHECK', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('TIER', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('VOI', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('LIME', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('BIRD', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('DOTT', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('OKAI EBIKE', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),

    # --- Telecom/Internet ---
    ('KPN', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('KPN MOBIEL', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('KPN THUIS', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('VODAFONE', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('VODAFONE MOBIEL', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('T-MOBILE', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('T-MOBILE NETHERLANDS', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('ZIGGO', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('TELE2', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('TELE2 NL', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('SIMYO', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('BEN', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('HOLLANDSNIEUWE', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('LEBARA', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('LYCAMOBILE', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('BUDGET MOBIEL', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('YOUFONE', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('ODIDO', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('ORANGE', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('VOICECOM', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('SPACETELE', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('TELFORT', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('CAIWAY', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('ASSIM', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('UPC', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('HORIZON BOX', 'vaste_lasten', 'Telecom/Internet', 0.92),
    ('ALLIANDER', 'vaste_lasten', 'Telecom/Internet', 0.92),

    # --- Energie ---
    ('VATTENFALL', 'vaste_lasten', 'Energie', 0.92),
    ('ENECO', 'vaste_lasten', 'Energie', 0.92),
    ('ESSENT', 'vaste_lasten', 'Energie', 0.92),
    ('GREENCHOICE', 'vaste_lasten', 'Energie', 0.92),
    ('BUDGET ENERGIE', 'vaste_lasten', 'Energie', 0.92),
    ('ENGIE', 'vaste_lasten', 'Energie', 0.92),
    ('VANDEBRON', 'vaste_lasten', 'Energie', 0.92),
    ('PURE ENERGIE', 'vaste_lasten', 'Energie', 0.92),
    ('OXXIO', 'vaste_lasten', 'Energie', 0.92),
    ('INNOVA ENERGIE', 'vaste_lasten', 'Energie', 0.92),
    ('QURRENT', 'vaste_lasten', 'Energie', 0.92),
    ('ZONNEPLAN', 'vaste_lasten', 'Energie', 0.92),
    ('LUMINA', 'vaste_lasten', 'Energie', 0.92),
    ('DELTA', 'vaste_lasten', 'Energie', 0.92),
    ('ENERGIEDIRECT', 'vaste_lasten', 'Energie', 0.92),
    ('ELECTRABEL', 'vaste_lasten', 'Energie', 0.92),
    ('ECONNEXT', 'vaste_lasten', 'Energie', 0.92),
    ('NUON', 'vaste_lasten', 'Energie', 0.92),
    ('POWERPEERS', 'vaste_lasten', 'Energie', 0.92),
    ('NEXT ENERGY', 'vaste_lasten', 'Energie', 0.92),

    # --- Water ---
    ('VITENS', 'vaste_lasten', 'Water', 0.92),
    ('DUNEA', 'vaste_lasten', 'Water', 0.92),
    ('BRABANT WATER', 'vaste_lasten', 'Water', 0.92),
    ('PWN NOORD HOLLAND', 'vaste_lasten', 'Water', 0.92),
    ('WATERNET AMSTERDAM', 'vaste_lasten', 'Water', 0.92),
    ('EVIDES', 'vaste_lasten', 'Water', 0.92),
    ('WMD', 'vaste_lasten', 'Water', 0.92),
    ('WATERSCHAP', 'vaste_lasten', 'Water', 0.92),
    ('RIJNLAND', 'vaste_lasten', 'Water', 0.92),
    ('DELFLAND', 'vaste_lasten', 'Water', 0.92),
    ('VALLEI EN VELUWE', 'vaste_lasten', 'Water', 0.92),

    # --- Verzekeringen ---
    ('ACHMEA', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('CENTRAAL BEHEER', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('INTERPOLIS', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('ZILVEREN KRUIS', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('FBTO', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('INSHARED', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('NATIONALE-NEDERLANDEN', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('ASR', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('AEGON', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('ALLIANZ', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('AGIS', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('CZ GROEP', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('CZ HEALTH', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('VGZ', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('MENZIS', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('OHRA', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('DITZO', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('PROMOVENDUM', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('UNIVÉ', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('ZLM', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('TVM', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('KLAVERBLAD', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('REAAL', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('DELTA LLOYD', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('GENERALI', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('AON', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('UNIGARANT', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('AAVIS', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('CAPELLE', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('COÖPERATIEF DELFT', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('DIVOSA', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('FBAO', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('GROOT INSURE', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('LEEUWARDER ASSURANTIE', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('MAAS ASSURANTIE', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('OOST ROTTERDAM', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('SAMENWERK GROEP', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('SYNTHAX', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('TABELANO', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('USXP', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('VUISTER ASSURANTIE', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('WADERSLOOOT ASSURANTIE', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('VERZEKERAAR', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('ZORGVERZEKERING', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('POLIS', 'vaste_lasten', 'Verzekeringen', 0.9),

    # --- Elektronica/Gadgets ---
    ('BOL.COM', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('AMAZON', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('AMAZON.NL', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('AMAZON EU', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('COOLBLUE', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('COOLBLUE.NL', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('MEDIAMARKT', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('MEDIA MARKT', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),

    # --- Kleding/Schoenen ---
    ('ZALANDO', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('ZALANDO.NL', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('H&M', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('HM ONLINE', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('ZARA', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('HEMA', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('HEMA.NL', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('ACTION', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('PRIMARK', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('BLOKKER', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('C&A', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('PRIT', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('MEXX', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('TOMMY HILFIGER', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('CALVIN KLEIN', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('POLO RALPH LAUREN', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('BANANA REPUBLIC', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('VANS', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('CONVERSE', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('TIMBERLAND', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('SAUCONY', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('PUMA', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('FILA', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('CROCS', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('UGG', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('REPLAY', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('DIESEL', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('HUGO BOSS', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('ASOS', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('ABOUTYOU', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('WEHKAMP', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('WEHKAMP.NL', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('BIJENKORF', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('BIJENKORF.NL', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('ALIEXPRESS', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('WISH', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('SHEIN', 'variabele_kosten', 'Kleding/Schoenen', 0.85),

    # --- Overig variabel ---
    ('TEMU', 'variabele_kosten', 'Overig variabel', 0.8),

    # --- Wonen/Interieur ---
    ('IKEA', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('IKEA.COM', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('GAMMA', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('GAMMA.NL', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('PRAXIS', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('PRAXIS.NL', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('HORNBACH', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('KARWEI', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('INTRATUIN', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('BAUMARKT', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('BOUWMARKT', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('BAUHAUS', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('LETSBUILD', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('LEENBAKKER', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('MAISONS DU MONDE', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('NATURA', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('KWANTUM', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('XOOON', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('WOOOD', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('FUTUREPROOF', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('ROOD SOFA', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('BOCONCEPT', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('KNOLL', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('VITRA', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('HAY', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('FLOS', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('MUUTO', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('NORM ARCHITECTS', 'variabele_kosten', 'Wonen/Interieur', 0.85),

    # --- Elektronica/Gadgets ---
    ('ELECTROLUX', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('SIEMENS', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('BOSCH', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('NEFF', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('MIELE', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('PHILIPS', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('SAMSUNG', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('LG ELECTRONICS', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('SONY', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('PANASONIC', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('WHIRLPOOL', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('ARCELIK', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('CANDY', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('GORENJE', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('VESTEL', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('BAUKNECHT', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),

    # --- Persoonlijke verzorging ---
    ('KRUIDVAT', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('ETOS', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('DA DROGISTERIJ', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('RITUALS', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('DOUGLAS', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('BOOTS', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),

    # --- Gezondheid/Apotheek ---
    ('HOLLAND & BARRETT', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('GNC', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('LUCOVITAAL', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('CENTELLAX', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('OPTIONEX', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),

    # --- Sport/Fitness ---
    ('DECATHLON', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('DECATHLON.NL', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('INTERSPORT', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('JD SPORTS', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('NIKE', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('ADIDAS', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('PUMA STORE', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('NEW BALANCE', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('ASICS', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('SALOMON', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('MERRELL', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('COLUMBIA', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('THE NORTH FACE', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('HAGLOFS', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('FJALLRAVEN', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('MOUNTAIN WAREHOUSE', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('COTSWOLD OUTDOOR', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('BLACKS OUTDOOR', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('GO OUTDOORS', 'variabele_kosten', 'Sport/Fitness', 0.85),

    # --- Huisdieren ---
    ('BITIBA', 'variabele_kosten', 'Huisdieren', 0.85),
    ('ZOOPLUS', 'variabele_kosten', 'Huisdieren', 0.85),
    ('DROOLS', 'variabele_kosten', 'Huisdieren', 0.85),
    ('DIERENWINKEL', 'variabele_kosten', 'Huisdieren', 0.85),
    ('PETSHOP', 'variabele_kosten', 'Huisdieren', 0.85),
    ('FAUNAZOO', 'variabele_kosten', 'Huisdieren', 0.85),
    ('PETCURE', 'variabele_kosten', 'Huisdieren', 0.85),

    # --- Entertainment/Vrije tijd ---
    ('STUBBORNLY BOOKS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('LIBRIS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('BOEKWINKELTJE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('STANDAARD BOEKHANDEL', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('BRUNA', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('WATERSTONES', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('STEAM', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('PLAYSTATION STORE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('XBOX STORE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('NINTENDO STORE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('EPIC GAMES', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('GAMERSG', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('GAMECITY', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('GAMEMANIA', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('INTERTOYS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('LEGO STORE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('LEGOMINIFIGURES', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('SPEELGOEDPALEIS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('TOY STORE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('TOYCHAMP', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),

    # --- Abonnementen/Lidmaatschappen ---
    ('NETFLIX', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('NETFLIX.NL', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('DISNEY+', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('DISNEYPLUS', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('HBO MAX', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('HBOMAX', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('VIDEOLAND', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('NPO START', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('KIJK', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('PATHE THUIS', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('FILMAX', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('VIAPLAY', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('CURIOSITY STREAM', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('SPOTIFY', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('SPOTIFY.COM', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('APPLE MUSIC', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('ITUNES MUSIC', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('YOUTUBE MUSIC', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('TIDAL', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('DEEZER', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('TIDAL HIFI', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('BANDCAMP', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('AUDIBLE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('STORYTEL', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('SCRIBD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('NRC', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('NRC.NL', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('VOLKSKRANT', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('AD.NL', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('TELEGRAAF', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('FD FINANCIEEL DAGBLAD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('BLENDLE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('MEDIUM', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('SUBSTACK', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('PATREON', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('MICROSOFT 365', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('OFFICE 365', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('ADOBE CREATIVE CLOUD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('ADOBE PHOTOSHOP', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('DROPBOX', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('GOOGLE ONE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('ICLOUD+', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('APPLE ONE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('NOTION', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('EVERNOTE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('SLACK', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('ZOOM', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('TEAMS MICROSOFT', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),

    # --- Gezondheid/Apotheek ---
    ('APOTHEEK', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('APOTHEKER', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('FARMACIA', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('FARMACIE', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('SPECSAVERS', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('HANS ANDERS', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('EYE WISH', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('PEARLE', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('FREEWAY OPTICS', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('KRAMER', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('BRILLENWINKEL', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('OPTICIEN', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('TANDARTS', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('TANDARTENPRAKTIJK', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('DENTALCENTRUM', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('TANDARTSENPRAKTIJK', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('ORTHODONTIE', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('HUISARTS', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('HUISARTENPRAKTIJK', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('FYSIOTHERAPEUT', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('FYSIOTHERAPIE', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('OSTEOPAAT', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('CHIROPRACTOR', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('MASSAGETHERAPIE', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('PSYCHOLOOG', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('PSYCHIATER', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('THERAPEUT', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('KLINIEK', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('ZIEKENHUIS', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('GEZONDHEIDSCENTRUM', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('HOMEOPAAT', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('ACUPUNCTUUR', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('ACUPUNCTURIST', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('NATUURPRAKTIJK', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('BODYANDFIT', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('MYFITNESSPAL', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('NUTRIPLEIN', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('POWERHOUSE', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('SUPPLEMENT STORE', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),

    # --- Abonnementen/Lidmaatschappen ---
    ('BASIC FIT', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('FIT FOR FREE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('ANYTIME FITNESS', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('SPORTCITY', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('TRAINMORE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('ONEFIT', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('CLASSPASS', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('FITX', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('PURE GYM', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('VIRGIN ACTIVE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('HEALTHCITY', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('POWER WORLD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('MOVEIT', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('YOGA STUDIO', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('YOGASTUDIO', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('DANSSTUDIO', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('DANSLES', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('TENNISVERENIGING', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('SPORTVERENIGING', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('VOETBALCLUB', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('ZWEMBAD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('SWIMBAD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('SPORTCOMPLEX', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),

    # --- Gemeentelijke heffingen ---
    ('GBLT', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('COCENSUS', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('BSGR', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('SABEWA', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('RMN DRENTHE', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('GEMEENTE', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('GEMEENTE AMSTERDAM', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('GEMEENTE ROTTERDAM', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('GEMEENTE UTRECHT', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('GEMEENTE GRONINGEN', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('GEMEENTE DEN HAAG', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('GEMEENTE EINDHOVEN', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('BELASTING', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('HEFFING', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('ERFPACHT', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('ONROEREND ZAAK BELASTING', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('OZB', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('RIOOLRECHT', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('AFVALSTOFFENHEFFING', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('AFVALINZAMELING', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('PARKEEROPZICHT', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),
    ('GRONDBELASTING', 'vaste_lasten', 'Gemeentelijke heffingen', 0.92),

    # --- Kinderopvang ---
    ('PARTOU', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('KINDERRIJK', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('SMALLSTEPS', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('KIDSFOUNDATION', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('CATALPA', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('COMPANANNY', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('BLOS', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('KINDEROPVANGCENTRUM', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('KINDEROPVANG', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('PEUTEROPVANG', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('CRÈCHE', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('PEUTERSPEELZAAL', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('BUITENSCHOOLSE OPVANG', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('BSO', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('KINDERDAGVERBLIJF', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('AFTERSCHO', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('KINDERCENTER', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('KLEUTERHUISJE', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('EDUCATIEF KINDEROPVANG', 'vaste_lasten', 'Kinderopvang', 0.9),

    # --- Onderwijs ---
    ('DUO', 'vaste_lasten', 'Onderwijs', 0.88),
    ('STUDIEFINANCERING', 'vaste_lasten', 'Onderwijs', 0.88),
    ('STUDIELINK', 'vaste_lasten', 'Onderwijs', 0.88),
    ('UNIVERSITEIT', 'vaste_lasten', 'Onderwijs', 0.88),
    ('UNIVERSITY', 'vaste_lasten', 'Onderwijs', 0.88),
    ('HOGESCHOOL', 'vaste_lasten', 'Onderwijs', 0.88),
    ('UVA AMSTERDAM', 'vaste_lasten', 'Onderwijs', 0.88),
    ('EUR ROTTERDAM', 'vaste_lasten', 'Onderwijs', 0.88),
    ('UU UTRECHT', 'vaste_lasten', 'Onderwijs', 0.88),
    ('RUG GRONINGEN', 'vaste_lasten', 'Onderwijs', 0.88),
    ('LEIDEN UNIVERSITY', 'vaste_lasten', 'Onderwijs', 0.88),
    ('TILBURG UNIVERSITY', 'vaste_lasten', 'Onderwijs', 0.88),
    ('MAASTRICHT UNIVERSITY', 'vaste_lasten', 'Onderwijs', 0.88),
    ('WAGENINGEN UNIVERSITY', 'vaste_lasten', 'Onderwijs', 0.88),
    ('OPEN UNIVERSITEIT', 'vaste_lasten', 'Onderwijs', 0.88),
    ('VU AMSTERDAM', 'vaste_lasten', 'Onderwijs', 0.88),
    ('SCHOOL', 'vaste_lasten', 'Onderwijs', 0.88),
    ('SCHOOLFONDS', 'vaste_lasten', 'Onderwijs', 0.88),
    ('SCHOOLGELD', 'vaste_lasten', 'Onderwijs', 0.88),
    ('PRIVÉ SCHOOL', 'vaste_lasten', 'Onderwijs', 0.88),
    ('INTERNATIONALE SCHOOL', 'vaste_lasten', 'Onderwijs', 0.88),
    ('MONTESSORI', 'vaste_lasten', 'Onderwijs', 0.88),
    ('WALDORF', 'vaste_lasten', 'Onderwijs', 0.88),

    # --- Entertainment/Vrije tijd ---
    ('TRAINING', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('CURSUS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('WORKSHOP', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('MASTERCLASS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('COACHING', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('COACHING SESSIE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('ONLINE KURS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),

    # --- Abonnementen/Lidmaatschappen ---
    ('SKILLSHARE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),

    # --- Entertainment/Vrije tijd ---
    ('UDEMY', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('COURSERA', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('EDIX', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),

    # --- Cadeaus/Donaties ---
    ('KWF', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('KWF KANKER BESTRIJDING', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('HARTSTICHTING', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('HARTSLAG AMSTERDAM', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('RODE KRUIS', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('RODE KRUIS NEDERLAND', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('ARTSEN ZONDER GRENZEN', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('ARTSEN ZONDER GRENZEN NEDERLAND', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('UNICEF', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('UNICEF NEDERLAND', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('WWF', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('WORLD WILDLIFE FUND', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('GREENPEACE', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('AMNESTY INTERNATIONAL', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('PLAN INTERNATIONAL', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('OXFAM NOVIB', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('CARE NEDERLAND', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('WORLD VISION', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('KIKA', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('STICHTING KIKA', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('RAUW', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('DIERENWERELD', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('FONDS SLUYTERMAN VAN LOY', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('SVENSKA KYRKAN', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('SALVATION ARMY', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('LEGER DES HEILS', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('STICHTING PEACE', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('KINDERRECHTENFONDS', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('STICHTING BETERE WERELD', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('DONATIE', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('DONEER', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('BENEFIET', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('GIRO 555', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('GIVING PLATFORM', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('GIVEITALL', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('IGIVEICAST', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('VERGEVEN', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('STICHTING WEIDEVZAAG', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),

    # --- Effectenrekening ---
    ('DEGIRO', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('BINCK', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('BINCK BANK', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('LYNX', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('INTERACTIVE BROKERS', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('SAXO', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('SAXO BANK', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('ABN AMRO BELEGGEN', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('ING BELEGGEN', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('RABO BELEGGEN', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('SNS BELEGGEN', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('KEMPEN ORANGE', 'sparen_beleggen', 'Effectenrekening', 0.92),

    # --- Spaarrekening ---
    ('MEESMAN', 'sparen_beleggen', 'Spaarrekening', 0.9),
    ('BRAND NEW DAY', 'sparen_beleggen', 'Spaarrekening', 0.9),
    ('INDEXFONDS', 'sparen_beleggen', 'Spaarrekening', 0.9),

    # --- Effectenrekening ---
    ('BELEGGINGSFONDS', 'sparen_beleggen', 'Effectenrekening', 0.92),

    # --- Spaarrekening ---
    ('SPAARRENTE', 'sparen_beleggen', 'Spaarrekening', 0.9),

    # --- Crypto ---
    ('BITVAVO', 'sparen_beleggen', 'Crypto', 0.88),
    ('COINBASE', 'sparen_beleggen', 'Crypto', 0.88),
    ('KRAKEN', 'sparen_beleggen', 'Crypto', 0.88),
    ('KRAKEN EXCHANGE', 'sparen_beleggen', 'Crypto', 0.88),
    ('BINANCE', 'sparen_beleggen', 'Crypto', 0.88),
    ('KUCOIN', 'sparen_beleggen', 'Crypto', 0.88),
    ('BYBIT', 'sparen_beleggen', 'Crypto', 0.88),
    ('GATE.IO', 'sparen_beleggen', 'Crypto', 0.88),
    ('HUOBI', 'sparen_beleggen', 'Crypto', 0.88),
    ('OKX', 'sparen_beleggen', 'Crypto', 0.88),
    ('CRYPTO.COM', 'sparen_beleggen', 'Crypto', 0.88),
    ('EXODUS WALLET', 'sparen_beleggen', 'Crypto', 0.88),
    ('COINOMI', 'sparen_beleggen', 'Crypto', 0.88),
    ('METAMASK', 'sparen_beleggen', 'Crypto', 0.88),
    ('LEDGER', 'sparen_beleggen', 'Crypto', 0.88),
    ('TREZOR', 'sparen_beleggen', 'Crypto', 0.88),

    # --- Effectenrekening ---
    ('TRADING 212', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('ETORO', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('PLUS500', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('CFD TRADING', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('FOREX', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('SPREAD BETTING', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('VANGUARD', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('BLACKROCK', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('ISHARES', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('XETRA', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('MSCI WORLD', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('MSCI EMERGING MARKETS', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('BERKSHIRE HATHAWAY', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('SP500', 'sparen_beleggen', 'Effectenrekening', 0.92),
    ('GOLD SPOT', 'sparen_beleggen', 'Effectenrekening', 0.92),

    # --- Overig variabel ---
    ('BELASTINGDIENST', 'variabele_kosten', 'Overig variabel', 0.8),
    ('BELASTINGAANGIFTE', 'variabele_kosten', 'Overig variabel', 0.8),
    ('INKOMSTENBELASTING', 'variabele_kosten', 'Overig variabel', 0.8),
    ('AANGIFTELOON', 'variabele_kosten', 'Overig variabel', 0.8),
    ('ANF VOOR STAKINGSUITKERINGEN', 'variabele_kosten', 'Overig variabel', 0.8),
    ('NETTO LOONBELASTINGEN', 'variabele_kosten', 'Overig variabel', 0.8),

    # --- Cadeaus/Donaties ---
    ('ANBI', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),

    # --- Overig variabel ---
    ('TOESLAGEN', 'variabele_kosten', 'Overig variabel', 0.8),
    ('POSTNL', 'variabele_kosten', 'Overig variabel', 0.8),
    ('POST NL', 'variabele_kosten', 'Overig variabel', 0.8),
    ('DHL', 'variabele_kosten', 'Overig variabel', 0.8),
    ('UPS', 'variabele_kosten', 'Overig variabel', 0.8),
    ('FEDEX', 'variabele_kosten', 'Overig variabel', 0.8),
    ('TNT EXPRESS', 'variabele_kosten', 'Overig variabel', 0.8),
    ('GLS', 'variabele_kosten', 'Overig variabel', 0.8),
    ('BRIEVENBUSPAKKET', 'variabele_kosten', 'Overig variabel', 0.8),
    ('ACCOUNTANT', 'variabele_kosten', 'Overig variabel', 0.8),
    ('ACCOUNTANTSKANTOOR', 'variabele_kosten', 'Overig variabel', 0.8),
    ('ADMINISTRATIE', 'variabele_kosten', 'Overig variabel', 0.8),
    ('ADMINISTRATIEKANTOOR', 'variabele_kosten', 'Overig variabel', 0.8),
    ('ADVIES', 'variabele_kosten', 'Overig variabel', 0.8),
    ('ADVOCAAT', 'variabele_kosten', 'Overig variabel', 0.8),
    ('ADVOKAAT KANTOOR', 'variabele_kosten', 'Overig variabel', 0.8),
    ('JURIDISCH ADVIES', 'variabele_kosten', 'Overig variabel', 0.8),
    ('NOTARIS', 'variabele_kosten', 'Overig variabel', 0.8),
    ('NOTARISKANTOOR', 'variabele_kosten', 'Overig variabel', 0.8),
    ('GERECHTSDEURWAARDER', 'variabele_kosten', 'Overig variabel', 0.8),
    ('BELASTINGADVISEUR', 'variabele_kosten', 'Overig variabel', 0.8),
    ('FINANCIEEL ADVISEUR', 'variabele_kosten', 'Overig variabel', 0.8),
    ('FINANCIAL ADVISOR', 'variabele_kosten', 'Overig variabel', 0.8),
    ('VERZEKERINGSADVISEUR', 'variabele_kosten', 'Overig variabel', 0.8),

    # --- Benzine/Diesel/Laden ---
    ('TANKSTATION', 'variabele_kosten', 'Benzine/Diesel/Laden', 0.9),

    # --- Auto/Mobiliteit ---
    ('GARAGE', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('GARAGEBEDRIJF', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('AUTOWERKPLAATS', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('AUTOBEDRIJF', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('AUTOGARAGE', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('SCHRADERIJ', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('AUTOWAS', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('CAR WASH', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('CARWASH', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('WASSTRAAT', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('AUTOVERZORGING', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('MOT KEURING', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('APK KEURING', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),

    # --- Wonen/Interieur ---
    ('WONINGBOUW', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('REPARATIE', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('SCHILDER', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('LOODGIETER', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('ELEKTRICIEN', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('TIMMERMAN', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('GLAZENWASSER', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('SCHOONMAAK', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('SCHOONMAAKBEDRIJF', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('TUINAANLEG', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('TUINONDERHOUD', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('HOVENIERS', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('GROENONDERHOUD', 'variabele_kosten', 'Wonen/Interieur', 0.85),

    # --- Kinderopvang ---
    ('KINDERKAMER', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('OPPAS', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('OPPASSERVICE', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('BABYSITTER', 'vaste_lasten', 'Kinderopvang', 0.9),

    # --- Huisdieren ---
    ('DIERENARTS', 'variabele_kosten', 'Huisdieren', 0.85),
    ('DIERENKLINIEK', 'variabele_kosten', 'Huisdieren', 0.85),
    ('DIERENHOSPITAAL', 'variabele_kosten', 'Huisdieren', 0.85),
    ('HONDENTRAINING', 'variabele_kosten', 'Huisdieren', 0.85),
    ('HONDENUITLAATSERVICE', 'variabele_kosten', 'Huisdieren', 0.85),
    ('PET GROOMING', 'variabele_kosten', 'Huisdieren', 0.85),
    ('DIERENVERZORGING', 'variabele_kosten', 'Huisdieren', 0.85),
    ('KENNEL', 'variabele_kosten', 'Huisdieren', 0.85),

    # --- Entertainment/Vrije tijd ---
    ('CINEMA', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('BIOSCOOP', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('FILMTHEATER', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('THEATER', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('CONCERT', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('MUZIEKHAL', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('MUSEUM', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('EXPOSITIE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('KUNSTGALERIE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('PRETPARK', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('ATTRACTIEPARK', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('DIERENTUIN', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('AQUARIUM', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('BOWLINGBAAN', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('BILJART', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('MINIGOLF', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('KARTING', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('ESCAPE ROOM', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('TRAMOLINE PARK', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),

    # --- Vakantie/Reizen ---
    ('HOTEL', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('BOOKING.COM', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('AIRBNB', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('EXPEDIA', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('TRIVAGO', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('KAYAK', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('RYANAIR', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('EASYJET', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('TRANSAVIA', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('KLM', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('AIRLINE', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('VLIEGTICKET', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('CRUISE', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('RONDREIZEN', 'variabele_kosten', 'Vakantie/Reizen', 0.85),

    # --- Overig variabel ---
    ('BANK', 'variabele_kosten', 'Overig variabel', 0.8),
    ('BANKGEBUREN', 'variabele_kosten', 'Overig variabel', 0.8),
    ('RENTEBETALING', 'variabele_kosten', 'Overig variabel', 0.8),
    ('RENTE', 'variabele_kosten', 'Overig variabel', 0.8),
    ('LENING', 'variabele_kosten', 'Overig variabel', 0.8),

    # --- Hypotheek/Huur ---
    ('HYPOTHEEK AFLOSSING', 'vaste_lasten', 'Hypotheek/Huur', 0.95),
    ('HUURRENTE', 'vaste_lasten', 'Hypotheek/Huur', 0.95),

    # --- Boodschappen/Supermarkt ---
    ('BAKKERIJ', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('BAKKER BART', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('BAKKER VAN MAANEN', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('SLAGERIJ', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('KEURSLAGER', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('VISWINKEL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('KAASWINKEL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('EKOPLAZA', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('MARQT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('STACH', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('BILDER & DE CLERCQ', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('DEEN', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('BOON', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('ATTENT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('TROEFMARKT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('AMAZING ORIENTAL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('TOKO', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.85),
    ('SLIGRO', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('MAKRO', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('HANOS', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('LANDMARKT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('HELLO FRESH', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('HELLOFRESH', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.92),
    ('FRESH.NL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('FLITSBEZORGING', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.85),
    ('ZAPP', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.85),
    ('THUISAFGEHAALD', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.85),
    ('BIORGANIC', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('LANDWAART', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('GALL & GALL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('GALL&GALL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('MITRA', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.9),
    ('DRANKGIGANT', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('DRANKDOZIJN', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('DIRCK III', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('BIERWINKEL', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),
    ('SLIJTERIJ', 'variabele_kosten', 'Boodschappen/Supermarkt', 0.88),

    # --- Horeca/Restaurants ---
    ('FIVE GUYS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('DUNKIN', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('DUNKIN DONUTS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('ANNE & MAX', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('COFFEE DISTRICT', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('THE BREAKFAST CLUB', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('IENS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('BISTRO', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('TRATTORIA', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('SUMO', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('WOK', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('KWALITARIA', 'variabele_kosten', 'Horeca/Restaurants', 0.88),
    ('EETHUIS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('GRANDCAFE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('GRAND CAFE', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('LUNCHROOM', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('BROODJESZAAK', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('BROODJESBAR', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('SNACKBAR', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CAFETARIA', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('FRITUUR', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('GRILLROOM', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('SHOARMA', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('KEBAB', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('DONER', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('TAPAS', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('DE HAVEN VAN TEXEL', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('RESTAURANT', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('RESTO', 'variabele_kosten', 'Horeca/Restaurants', 0.8),
    ('CATERING', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('PARTY CATERING', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('JACK ASTORS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('WAGAMAMA', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('NANDOS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('NANDO\'S', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('TGI FRIDAY', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('PANCAKES', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('PANNENKOEK', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('IJSSALON', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('POKE BOWL', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('POKEBOWL', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('SATE', 'variabele_kosten', 'Horeca/Restaurants', 0.8),
    ('WOKRESTAURANT', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CHINEES RESTAURANT', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CHINEES-INDISCH', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('INDONESISCH', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('ITALIAANS RESTAURANT', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('GRIEKS RESTAURANT', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('INDIAAS', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('THAIS', 'variabele_kosten', 'Horeca/Restaurants', 0.8),
    ('JAPANS', 'variabele_kosten', 'Horeca/Restaurants', 0.8),
    ('MEXICAANS', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('TACO BELL', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('POPEYES', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('PAPA JOHNS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('SPARE RIB EXPRESS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('SMULLERS', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('JULIA', 'variabele_kosten', 'Horeca/Restaurants', 0.8),
    ('BEREN', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('DE BEREN', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('DOPPIO', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('ESPRESSOBAR', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('BIERTUIN', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('BROUWERIJ', 'variabele_kosten', 'Horeca/Restaurants', 0.82),
    ('PROEFLOKAAL', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('WIJNBAR', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('COCKTAILBAR', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('NACHTCLUB', 'variabele_kosten', 'Horeca/Restaurants', 0.85),
    ('CLUB', 'variabele_kosten', 'Horeca/Restaurants', 0.78),

    # --- Vakantie/Reizen ---
    ('BILDERBERG', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('BASTION HOTEL', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('CARLTON HOTEL', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('AMRATH', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('BEST WESTERN', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('MERCURE', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('ACCOR', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('RADISSON', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('CROWNE PLAZA', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('HYATT', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('MOTEL ONE', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('PARK PLAZA', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('SHERATON', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('WESTIN', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('W HOTEL', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('RENAISSANCE HOTEL', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('HAMPTON INN', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('COURTYARD', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('SWISSOTEL', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('HOSTEL', 'variabele_kosten', 'Vakantie/Reizen', 0.82),
    ('B&B', 'variabele_kosten', 'Vakantie/Reizen', 0.8),
    ('PENSION', 'variabele_kosten', 'Vakantie/Reizen', 0.8),

    # --- Kleding/Schoenen ---
    ('MANGO', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('MASSIMO DUTTI', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('PULL&BEAR', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('PULL & BEAR', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('BERSHKA', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('STRADIVARIUS', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('COS STORE', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('ARKET', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('& OTHER STORIES', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('MONKI', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('WEEKDAY', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('SCOTCH & SODA', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('G-STAR', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('DENHAM', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('SUITSUPPLY', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('SUIT SUPPLY', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('RALPH LAUREN', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('GUESS', 'variabele_kosten', 'Kleding/Schoenen', 0.82),
    ('JACK & JONES', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('ONLY', 'variabele_kosten', 'Kleding/Schoenen', 0.8),
    ('VERO MODA', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('RIVER ISLAND', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('URBAN OUTFITTERS', 'variabele_kosten', 'Kleding/Schoenen', 0.85),

    # --- Vakantie/Reizen ---
    ('WEEKENDJE WEG', 'variabele_kosten', 'Vakantie/Reizen', 0.85),

    # --- Kleding/Schoenen ---
    ('GAP', 'variabele_kosten', 'Kleding/Schoenen', 0.82),
    ('OLD NAVY', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('OYSHO', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('AMERICA TODAY', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('WE FASHION', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('STEPS', 'variabele_kosten', 'Kleding/Schoenen', 0.82),
    ('MISS ETAM', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('ZEEMAN', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('TAKKO', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('BRISTOL', 'variabele_kosten', 'Kleding/Schoenen', 0.82),
    ('SHOEBY', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('CHASIN', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('GARCIA', 'variabele_kosten', 'Kleding/Schoenen', 0.82),
    ('SANDWICH', 'variabele_kosten', 'Kleding/Schoenen', 0.8),
    ('EXPRESSO FASHION', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('COOLCAT', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('TER STAL', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('KIDSPLANET', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('PRENATAL', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('BABYPARK', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('NOPPIES', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('VAN HAREN', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('NELSON SCHOENEN', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('MANFIELD', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('INVITO', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('DOLCIS', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('SACHA', 'variabele_kosten', 'Kleding/Schoenen', 0.82),
    ('OMODA', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('NIKE STORE', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('ADIDAS STORE', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('FOOT LOCKER', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('FOOTLOCKER', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('SNIPES', 'variabele_kosten', 'Kleding/Schoenen', 0.85),
    ('SNEAKER DISTRICT', 'variabele_kosten', 'Kleding/Schoenen', 0.85),

    # --- Wonen/Interieur ---
    ('LEEN BAKKER', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('JYSK', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('CASA', 'variabele_kosten', 'Wonen/Interieur', 0.82),
    ('XENOS', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('FLYING TIGER', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('SOSTRENE GRENE', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('RIVERDALE', 'variabele_kosten', 'Wonen/Interieur', 0.82),
    ('LOODS 5', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('GOOSSENS', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('EIJERKAMP', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('PIET KLERKX', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('BETER BED', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('SWISS SENSE', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('AUPING', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('EMMA MATRAS', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('BEDDENREUS', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('SLEEPWORLD', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('SCHILDERSBEDRIJF', 'variabele_kosten', 'Wonen/Interieur', 0.82),
    ('FLEXA', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('HISTOR', 'variabele_kosten', 'Wonen/Interieur', 0.82),
    ('VERFWINKEL', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('HUBO', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('FORMIDO', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('MULTIMATE', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('BOSCH PROFESSIONAL', 'variabele_kosten', 'Wonen/Interieur', 0.82),
    ('TOOLSTATION', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('TUINCENTRUM', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('GROENRIJK', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('TUINLAND', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('TUIN & DIER', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('BOERENBOND', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('WELKOOP', 'variabele_kosten', 'Wonen/Interieur', 0.85),

    # --- Elektronica/Gadgets ---
    ('BELSIMPEL', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('MOBIEL.NL', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('SAMSUNG STORE', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('APPLE STORE', 'variabele_kosten', 'Elektronica/Gadgets', 0.88),
    ('MICROSOFT STORE', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('EXPERT', 'variabele_kosten', 'Elektronica/Gadgets', 0.82),
    ('BCC', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('PARADIGIT', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('ALTERNATE', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('AZERTY', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('MEGEKKO', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('TWEAKERS', 'variabele_kosten', 'Elektronica/Gadgets', 0.82),
    ('INFORMATIQUE', 'variabele_kosten', 'Elektronica/Gadgets', 0.82),
    ('GAME MANIA', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('BART SMIT', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('PLAYSTATION', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('XBOX', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),
    ('NINTENDO', 'variabele_kosten', 'Elektronica/Gadgets', 0.85),

    # --- Gezondheid/Apotheek ---
    ('HUISARTSENPRAKTIJK', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('HUISARTSEN', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('MEDISCH CENTRUM', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('TANDARTSPRAKTIJK', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('MONDHYGIEN', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('ORTHODONTIST', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('FYSIOTHERAP', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('FYSIO', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),
    ('CHIROPRACT', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),
    ('PODOTHERAP', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),
    ('PSYCHOTHERAP', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),
    ('GGZ', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),
    ('HOSPITAL', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('LABORATORIUM', 'variabele_kosten', 'Gezondheid/Apotheek', 0.82),
    ('BLOEDBANK', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),
    ('TROMBOSE', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),
    ('VERLOSKUNDIG', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('KRAAMZORG', 'variabele_kosten', 'Gezondheid/Apotheek', 0.88),
    ('OPTICIAN', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),
    ('OPTIEK', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),
    ('BRILLEN', 'variabele_kosten', 'Gezondheid/Apotheek', 0.82),
    ('CONTACTLENZEN', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),
    ('LENSWORLD', 'variabele_kosten', 'Gezondheid/Apotheek', 0.85),

    # --- Huisdieren ---
    ('DIERENZIEKENHUIS', 'variabele_kosten', 'Huisdieren', 0.88),

    # --- Persoonlijke verzorging ---
    ('KAPPER', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('HAIRSTUDIO', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('HAIR', 'variabele_kosten', 'Persoonlijke verzorging', 0.78),
    ('BARBIER', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('BARBER', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('SCHOONHEIDSSALON', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('BEAUTYSALON', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('BEAUTY', 'variabele_kosten', 'Persoonlijke verzorging', 0.78),
    ('NAGELSALON', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('NAGELSTUDIO', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('TANNING', 'variabele_kosten', 'Persoonlijke verzorging', 0.82),
    ('ZONNEBANK', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('SUNMINUTES', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('SPA', 'variabele_kosten', 'Persoonlijke verzorging', 0.8),
    ('SAUNA', 'variabele_kosten', 'Persoonlijke verzorging', 0.82),
    ('THERMEN', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('THERMAE', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('WELLNESS', 'variabele_kosten', 'Persoonlijke verzorging', 0.82),
    ('MASSAGE', 'variabele_kosten', 'Persoonlijke verzorging', 0.82),
    ('PARFUMERIE', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('ICI PARIS', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('SEPHORA', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('LUSH', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('BODY SHOP', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),
    ('YVES ROCHER', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),

    # --- Huisdieren ---
    ('PETS PLACE', 'variabele_kosten', 'Huisdieren', 0.88),
    ('DIERENSPECIAALZAAK', 'variabele_kosten', 'Huisdieren', 0.88),
    ('RANZIJN', 'variabele_kosten', 'Huisdieren', 0.88),
    ('DISCUS', 'variabele_kosten', 'Huisdieren', 0.82),
    ('BEEZTEES', 'variabele_kosten', 'Huisdieren', 0.85),
    ('MEDPETS', 'variabele_kosten', 'Huisdieren', 0.85),
    ('DIERAPOTHEKER', 'variabele_kosten', 'Huisdieren', 0.85),
    ('HONDENUITLAAT', 'variabele_kosten', 'Huisdieren', 0.85),
    ('TRIMSALON', 'variabele_kosten', 'Huisdieren', 0.85),
    ('HONDENSCHOOL', 'variabele_kosten', 'Huisdieren', 0.85),
    ('DIERENPENSION', 'variabele_kosten', 'Huisdieren', 0.85),
    ('CATERPET', 'variabele_kosten', 'Huisdieren', 0.85),

    # --- Vakantie/Reizen ---
    ('BOOKING COM', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('HOTELS.COM', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('VLIEGWINKEL', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('SKYSCANNER', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('MOMONDO', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('CORENDON', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('SUNWEB', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('TRAVELBIRD', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('D-REIZEN', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('REISBUREAU', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('TUI', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('THOMAS COOK', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('VUELING', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('WIZZ AIR', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('WIZZAIR', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('NORWEGIAN', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('LUFTHANSA', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('BRITISH AIRWAYS', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('AIR FRANCE', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('EUROWINGS', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('TURKISH AIRLINES', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('EMIRATES', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('FLIXBUS', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('EUROSTAR', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('THALYS', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('EUROLINES', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('STENA LINE', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('DFDS', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('P&O FERRIES', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('CENTER PARCS', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('CENTERPARCS', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('LANDAL', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('ROOMPOT', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('EUROCAMP', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('HUTTOPIA', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('RECREATIEPARK', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('VAKANTIEPARK', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('DROOMPARKEN', 'variabele_kosten', 'Vakantie/Reizen', 0.88),
    ('MOLENVELDSE HOEVE', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('BUDGET RENT', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('ENTERPRISE RENT', 'variabele_kosten', 'Vakantie/Reizen', 0.85),
    ('SUNNY CARS', 'variabele_kosten', 'Vakantie/Reizen', 0.88),

    # --- Entertainment/Vrije tijd ---
    ('PATHE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('KINEPOLIS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('VUE CINEMA', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('SCHOUWBURG', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('STADSSCHOUWBURG', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('CONCERTGEBOUW', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('ZIGGO DOME', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('AFAS LIVE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('AHOY', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('JAARBEURS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.82),
    ('RAI', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.8),
    ('ARTIS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('EFTELING', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('WALIBI', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('DUINRELL', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('SLAGHAREN', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('TOVERLAND', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('JULIANATOREN', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('MADURODAM', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('DOLFINARIUM', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('BURGERS ZOO', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('DIERGAARDE BLIJDORP', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('WILDLANDS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('BEEKSE BERGEN', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('APENHEUL', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('RIJKSMUSEUM', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('VAN GOGH MUSEUM', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('STEDELIJK MUSEUM', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('MAURITSHUIS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('NEMO', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.82),
    ('NATURALIS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('TICKETMASTER', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.88),
    ('EVENTIM', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('EVENTBRITE', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('TOPTICKETS', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('SPEELTUIN', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.82),
    ('KLIMPARK', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('FUNPARK', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('BOWLEN', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('BOWLING', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('KARTBAAN', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('LASER GAME', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),
    ('PAINTBALL', 'variabele_kosten', 'Entertainment/Vrije tijd', 0.85),

    # --- Sport/Fitness ---
    ('GOLFBAAN', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('TENNISCLUB', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('HOCKEYCLUB', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('SPORTCLUB', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('SPORTHAL', 'variabele_kosten', 'Sport/Fitness', 0.85),

    # --- Abonnementen/Lidmaatschappen ---
    ('PARAMOUNT', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('PARAMOUNT+', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('DISCOVERY+', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('CRUNCHYROLL', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('DAZN', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('ESPN', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('ADOBE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('CREATIVE CLOUD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('CHATGPT', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('OPENAI', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('ANTHROPIC', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('CLAUDE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.82),
    ('TEAMS', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.8),
    ('CANVA', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('FIGMA', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('GITHUB', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('TODOIST', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('1PASSWORD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('LASTPASS', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('BITWARDEN', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('NORD VPN', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('NORDVPN', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('SURFSHARK', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('EXPRESSVPN', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('MCAFEE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('NORTON', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('KASPERSKY', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('GRAMMARLY', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('HEADSPACE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('CALM APP', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('STRAVA', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('DUOLINGO', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('BABBEL', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('LINKEDIN PREMIUM', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('LINKEDIN', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.82),
    ('TROUW', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('PAROOL', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('LEEUWARDER COURANT', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('TUBANTIA', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('GELDERLANDER', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('BRABANTS DAGBLAD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('BN DE STEM', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('PZC', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.82),
    ('DAGBLAD VAN HET NOORDEN', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('HAARLEMS DAGBLAD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('LEIDSCH DAGBLAD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('NOORDHOLLANDS DAGBLAD', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('DE LIMBURGER', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('QUEST', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.82),
    ('NATIONAL GEOGRAPHIC', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('DONALD DUCK', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('SANOMA', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('DPG MEDIA', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('TINDER', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('BUMBLE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('HAPPN', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('HINGE', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('PARSHIP', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),
    ('CONSUMENTENBOND', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),
    ('KASSA', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.8),
    ('BIBLIOTHEEK', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.85),

    # --- Cadeaus/Donaties ---
    ('VLUCHTELINGENWERK', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('CLINICLOWNS', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('STICHTING AANDEEL', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('DIERENBESCHERMING', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('NATUURMONUMENTEN', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('STAATSBOSBEHEER', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('WARCHILD', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('WAR CHILD', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('SOS KINDERDORPEN', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('MILIEUDEFENSIE', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('CORDAID', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('TEAR', 'variabele_kosten', 'Cadeaus/Donaties', 0.8),
    ('GIFT AAN', 'variabele_kosten', 'Cadeaus/Donaties', 0.8),
    ('COLLECTE', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('KERK', 'variabele_kosten', 'Cadeaus/Donaties', 0.78),
    ('PAROCHIE', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('MOSKEE', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),

    # --- Verzekeringen ---
    ('ZORG EN ZEKERHEID', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('DSW', 'vaste_lasten', 'Verzekeringen', 0.88),
    ('ENO ZORGVERZEKERAAR', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('SALLAND ZORGVERZEKERING', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('CARESQ', 'vaste_lasten', 'Verzekeringen', 0.85),
    ('JUST', 'vaste_lasten', 'Verzekeringen', 0.8),
    ('AVERO ACHMEA', 'vaste_lasten', 'Verzekeringen', 0.9),
    ('DE AMERSFOORTSE', 'vaste_lasten', 'Verzekeringen', 0.88),
    ('TAF', 'vaste_lasten', 'Verzekeringen', 0.82),
    ('ELIPS LEVEN', 'vaste_lasten', 'Verzekeringen', 0.85),
    ('BRAND NEW DAY VERZEKERING', 'vaste_lasten', 'Verzekeringen', 0.88),
    ('YARDEN', 'vaste_lasten', 'Verzekeringen', 0.88),
    ('DELA', 'vaste_lasten', 'Verzekeringen', 0.88),
    ('MONUTA', 'vaste_lasten', 'Verzekeringen', 0.88),
    ('NUVEMA', 'vaste_lasten', 'Verzekeringen', 0.85),
    ('POLISWIJZER', 'vaste_lasten', 'Verzekeringen', 0.82),
    ('VERZEKERUZELF', 'vaste_lasten', 'Verzekeringen', 0.82),
    ('BESURED', 'vaste_lasten', 'Verzekeringen', 0.85),
    ('LANCYR', 'vaste_lasten', 'Verzekeringen', 0.85),
    ('HEMA VERZEKERING', 'vaste_lasten', 'Verzekeringen', 0.88),

    # --- Auto/Mobiliteit ---
    ('BANDENCENTRALE', 'variabele_kosten', 'Auto/Mobiliteit', 0.88),
    ('PROFILE TYRECENTER', 'variabele_kosten', 'Auto/Mobiliteit', 0.88),
    ('EUROMASTER', 'variabele_kosten', 'Auto/Mobiliteit', 0.88),
    ('FIRST STOP', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('KWIK FIT', 'variabele_kosten', 'Auto/Mobiliteit', 0.88),
    ('KWIKFIT', 'variabele_kosten', 'Auto/Mobiliteit', 0.88),
    ('HALFORDS', 'variabele_kosten', 'Auto/Mobiliteit', 0.88),
    ('CARGLASS', 'variabele_kosten', 'Auto/Mobiliteit', 0.88),
    ('AUTORUIT', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('RDW', 'variabele_kosten', 'Auto/Mobiliteit', 0.88),
    ('MOTORRIJTUIG', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),

    # --- Gemeentelijke heffingen ---
    ('WEGENBELASTING', 'vaste_lasten', 'Gemeentelijke heffingen', 0.9),

    # --- Auto/Mobiliteit ---
    ('PARKEERGARAGE', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('PARKEERAUTOMAAT', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('PARKEERBON', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('VERKEERSBOETE', 'variabele_kosten', 'Auto/Mobiliteit', 0.88),
    ('CJIB', 'variabele_kosten', 'Auto/Mobiliteit', 0.9),
    ('SNELWEG', 'variabele_kosten', 'Auto/Mobiliteit', 0.82),
    ('TOLWEG', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('LIEFHEBBER', 'variabele_kosten', 'Auto/Mobiliteit', 0.78),
    ('PECHHULP', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('AUTOHUUR', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('CHECK DEELSCOOTER', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('TIER SCOOTER', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('BOLT', 'variabele_kosten', 'Auto/Mobiliteit', 0.82),
    ('UBER', 'variabele_kosten', 'Auto/Mobiliteit', 0.85),
    ('UBER TRIP', 'variabele_kosten', 'Auto/Mobiliteit', 0.88),
    ('TAXI', 'variabele_kosten', 'Auto/Mobiliteit', 0.82),

    # --- Kinderopvang ---
    ('GASTOUDER', 'vaste_lasten', 'Kinderopvang', 0.88),
    ('GASTOUDERBUREAU', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('NANNY', 'vaste_lasten', 'Kinderopvang', 0.82),
    ('BABYSIT', 'vaste_lasten', 'Kinderopvang', 0.8),
    ('HUMANITAS KINDEROPVANG', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('KOREIN', 'vaste_lasten', 'Kinderopvang', 0.88),
    ('KIDION', 'vaste_lasten', 'Kinderopvang', 0.88),
    ('KOBER', 'vaste_lasten', 'Kinderopvang', 0.88),
    ('STICHTING KINDEROPVANG', 'vaste_lasten', 'Kinderopvang', 0.9),
    ('SKE KINDEROPVANG', 'vaste_lasten', 'Kinderopvang', 0.9),

    # --- Onderwijs ---
    ('RIJKSUNIVERSITEIT', 'vaste_lasten', 'Onderwijs', 0.88),
    ('COLLEGEGELD', 'vaste_lasten', 'Onderwijs', 0.9),
    ('LESGELD', 'vaste_lasten', 'Onderwijs', 0.88),
    ('BIJLES', 'vaste_lasten', 'Onderwijs', 0.85),
    ('HUISWERKBEGELEIDING', 'vaste_lasten', 'Onderwijs', 0.85),
    ('MUZIEKSCHOOL', 'vaste_lasten', 'Onderwijs', 0.85),
    ('MUZIEKLES', 'vaste_lasten', 'Onderwijs', 0.85),
    ('RIJSCHOOL', 'vaste_lasten', 'Onderwijs', 0.88),
    ('RIJLES', 'vaste_lasten', 'Onderwijs', 0.88),
    ('CBR', 'vaste_lasten', 'Onderwijs', 0.88),
    ('AUTORIJSCHOOL', 'vaste_lasten', 'Onderwijs', 0.88),
    ('OPLEIDING', 'vaste_lasten', 'Onderwijs', 0.82),
    ('OUDERRAAD', 'vaste_lasten', 'Onderwijs', 0.82),
    ('OUDERBIJDRAGE', 'vaste_lasten', 'Onderwijs', 0.85),
    ('STUDYSTORE', 'vaste_lasten', 'Onderwijs', 0.85),
    ('STUVIA', 'vaste_lasten', 'Onderwijs', 0.82),

    # --- Overig variabel ---
    ('ETSY', 'variabele_kosten', 'Overig variabel', 0.82),

    # --- Kleding/Schoenen ---
    ('VINTED', 'variabele_kosten', 'Kleding/Schoenen', 0.82),

    # --- Overig variabel ---
    ('MARKTPLAATS', 'variabele_kosten', 'Overig variabel', 0.8),
    ('EBAY', 'variabele_kosten', 'Overig variabel', 0.8),
    ('THUISWINKEL', 'variabele_kosten', 'Overig variabel', 0.78),

    # --- Persoonlijke verzorging ---
    ('ICIPARISXL', 'variabele_kosten', 'Persoonlijke verzorging', 0.85),

    # --- Wonen/Interieur ---
    ('FONQ', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('WESTWING', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('VIDAXL', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('FLINDERS', 'variabele_kosten', 'Wonen/Interieur', 0.85),
    ('WAYFAIR', 'variabele_kosten', 'Wonen/Interieur', 0.85),

    # --- Openbaar vervoer ---
    ('BRENG', 'variabele_kosten', 'Openbaar vervoer', 0.85),
    ('EBS', 'variabele_kosten', 'Openbaar vervoer', 0.82),
    ('SYNTUS', 'variabele_kosten', 'Openbaar vervoer', 0.85),
    ('KEOLIS', 'variabele_kosten', 'Openbaar vervoer', 0.85),
    ('WATERBUS', 'variabele_kosten', 'Openbaar vervoer', 0.85),
    ('VEER', 'variabele_kosten', 'Openbaar vervoer', 0.78),
    ('PONT', 'variabele_kosten', 'Openbaar vervoer', 0.78),
    ('TREIN', 'variabele_kosten', 'Openbaar vervoer', 0.82),
    ('INTERCITY', 'variabele_kosten', 'Openbaar vervoer', 0.85),
    ('SPRINTER', 'variabele_kosten', 'Openbaar vervoer', 0.82),
    ('TRAM', 'variabele_kosten', 'Openbaar vervoer', 0.8),
    ('METRO', 'variabele_kosten', 'Openbaar vervoer', 0.78),
    ('BUS', 'variabele_kosten', 'Openbaar vervoer', 0.75),

    # --- Overig variabel ---
    ('DPD', 'variabele_kosten', 'Overig variabel', 0.82),
    ('BUDBEE', 'variabele_kosten', 'Overig variabel', 0.82),
    ('BRENGER', 'variabele_kosten', 'Overig variabel', 0.82),

    # --- Sport/Fitness ---
    ('SPORTSCHOOL', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('GYM', 'variabele_kosten', 'Sport/Fitness', 0.82),
    ('FITNESS', 'variabele_kosten', 'Sport/Fitness', 0.82),
    ('CROSSFIT', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('YOGA', 'variabele_kosten', 'Sport/Fitness', 0.82),
    ('PILATES', 'variabele_kosten', 'Sport/Fitness', 0.82),
    ('BOULDERHAL', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('KLIMHAL', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('URBAN SPORTS', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('VIRTUAGYM', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('FITCHANNEL', 'variabele_kosten', 'Sport/Fitness', 0.85),
    ('DAVID LLOYD', 'variabele_kosten', 'Sport/Fitness', 0.88),

    # --- Effectenrekening ---
    ('PEAKS', 'sparen_beleggen', 'Effectenrekening', 0.88),
    ('BUXZERO', 'sparen_beleggen', 'Effectenrekening', 0.88),
    ('BUX ZERO', 'sparen_beleggen', 'Effectenrekening', 0.88),
    ('FREEDOM24', 'sparen_beleggen', 'Effectenrekening', 0.88),
    ('FLATEX', 'sparen_beleggen', 'Effectenrekening', 0.88),
    ('REVOLUT', 'sparen_beleggen', 'Effectenrekening', 0.82),

    # --- Crypto ---
    ('NEXO', 'sparen_beleggen', 'Crypto', 0.88),
    ('CELSIUS', 'sparen_beleggen', 'Crypto', 0.85),
    ('BLOCKCHAIN', 'sparen_beleggen', 'Crypto', 0.82),
    ('CRYPTO', 'sparen_beleggen', 'Crypto', 0.82),
    ('BITCOIN', 'sparen_beleggen', 'Crypto', 0.85),
    ('LITEBIT', 'sparen_beleggen', 'Crypto', 0.88),
    ('SATOS', 'sparen_beleggen', 'Crypto', 0.85),

    # --- Energie ---
    ('DUTCH POWER', 'vaste_lasten', 'Energie', 0.9),
    ('COOLBLUE ENERGIE', 'vaste_lasten', 'Energie', 0.9),
    ('ENSTROGA', 'vaste_lasten', 'Energie', 0.88),
    ('DELTA ENERGIE', 'vaste_lasten', 'Energie', 0.9),
    ('TIBBER', 'vaste_lasten', 'Energie', 0.88),
    ('FRANK ENERGIE', 'vaste_lasten', 'Energie', 0.9),
    ('EASY ENERGY', 'vaste_lasten', 'Energie', 0.88),
    ('HUISMERK ENERGIE', 'vaste_lasten', 'Energie', 0.88),
    ('FENOR', 'vaste_lasten', 'Energie', 0.85),
    ('LIANDER', 'vaste_lasten', 'Energie', 0.88),
    ('STEDIN', 'vaste_lasten', 'Energie', 0.88),
    ('ENEXIS', 'vaste_lasten', 'Energie', 0.88),
    ('COTEQ', 'vaste_lasten', 'Energie', 0.85),
    ('WESTLAND INFRA', 'vaste_lasten', 'Energie', 0.85),

    # --- Telecom/Internet ---
    ('DELTA FIBER', 'vaste_lasten', 'Telecom/Internet', 0.9),
    ('ONLINE.NL', 'vaste_lasten', 'Telecom/Internet', 0.88),
    ('FREEDOM', 'vaste_lasten', 'Telecom/Internet', 0.8),
    ('KLIKSAFE', 'vaste_lasten', 'Telecom/Internet', 0.85),
    ('SIMPEL', 'vaste_lasten', 'Telecom/Internet', 0.88),
    ('ROBIN MOBILE', 'vaste_lasten', 'Telecom/Internet', 0.88),
    ('VOICEWORKS', 'vaste_lasten', 'Telecom/Internet', 0.85),
    ('GLASVEZEL', 'vaste_lasten', 'Telecom/Internet', 0.85),
    ('FIBER', 'vaste_lasten', 'Telecom/Internet', 0.8),

    # --- Overig variabel ---
    ('JURIDISCH', 'variabele_kosten', 'Overig variabel', 0.82),
    ('BOEKHOUDER', 'variabele_kosten', 'Overig variabel', 0.85),
    ('MAKELAAR', 'variabele_kosten', 'Overig variabel', 0.85),
    ('MAKELAARDIJ', 'variabele_kosten', 'Overig variabel', 0.85),
    ('HYPOTHEEKADVIES', 'variabele_kosten', 'Overig variabel', 0.85),
    ('TUINMAN', 'variabele_kosten', 'Overig variabel', 0.82),
    ('INSTALLATEUR', 'variabele_kosten', 'Overig variabel', 0.82),
    ('STOMERIJ', 'variabele_kosten', 'Overig variabel', 0.85),
    ('WASSERETTE', 'variabele_kosten', 'Overig variabel', 0.85),
    ('DRUKKERIJ', 'variabele_kosten', 'Overig variabel', 0.82),
    ('COPYSHOP', 'variabele_kosten', 'Overig variabel', 0.82),
    ('THE READ SHOP', 'variabele_kosten', 'Overig variabel', 0.85),
    ('READSHOP', 'variabele_kosten', 'Overig variabel', 0.85),
    ('BOEKHANDEL', 'variabele_kosten', 'Overig variabel', 0.82),
    ('BOL COM', 'variabele_kosten', 'Overig variabel', 0.85),

    # --- Abonnementen/Lidmaatschappen ---
    ('AMAZON PRIME', 'vaste_lasten', 'Abonnementen/Lidmaatschappen', 0.88),

    # --- Overig variabel ---
    ('OTTO', 'variabele_kosten', 'Overig variabel', 0.82),
    ('HEMA ONLINE', 'variabele_kosten', 'Overig variabel', 0.85),

    # --- Cadeaus/Donaties ---
    ('BLOEMEN', 'variabele_kosten', 'Cadeaus/Donaties', 0.78),
    ('BLOEMIST', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('EUROFLORIST', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('GREETZ', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('HALLMARK', 'variabele_kosten', 'Cadeaus/Donaties', 0.82),
    ('KAARTJE2GO', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('LOLAFLORA', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
    ('FLEUROP', 'variabele_kosten', 'Cadeaus/Donaties', 0.85),
]
